from supabase import create_client, Client

SUPABASE_URL = "https://jrbozblfmecmyxkdfgtx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyYm96YmxmbWVjbXl4a2RmZ3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0NTUxMDQsImV4cCI6MjA3OTAzMTEwNH0.YqIy_CAlnE3aqnbEokn-AiV5eq0td0t5jh3O8cxgat8"

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
